site_name: My Docs


plugins:
  - mkdocstrings:
        enabled: true
        custom_templates: templates
        default_handler: python
        handlers:
            python:
                options:
                    show_source: false

theme:
  name: "material"
